version: "3.4"
services:
  rabbit:
    image: "rabbitmq:3.8.3-management-alpine"
    ports:
      - "5671:5671"   # For TLS
      - "15671:15671" # For UI (HTTP)
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_PASSWORD}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_USERNAME}"
      RABBITMQ_SSL_CACERTFILE: "/cert/ca_certificate.pem"
      RABBITMQ_SSL_CERTFILE: "/cert/server_certificate.pem"
      RABBITMQ_SSL_KEYFILE: "/cert/server_key.pem"
      RABBITMQ_SSL_VERIFY: "verify_peer"
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "true"
    volumes:
      - "./cert:/cert"
    env_file:
      - .env 

  app:
    build: .
    image: webhook-controller
    ports:
      - "8080:8089"
    env_file:
      - .env 


